-- 코드를 입력하세요
SELECT C.CART_ID FROM (
    SELECT CART_ID , NAME
    FROM CART_PRODUCTS 
    WHERE NAME IN ("Milk" , "Yogurt")
    GROUP BY CART_ID , NAME
) AS C 
GROUP BY C.CART_ID
HAVING COUNT(C.CART_ID) >=2


