SELECT C.CATEGORY , C.MAX_PRICE , FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN (
    SELECT CATEGORY , MAX(PRICE) AS "MAX_PRICE" 
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
    ORDER BY MAX_PRICE DESC
) AS C ON FP.CATEGORY = C.CATEGORY AND FP.PRICE = C.MAX_PRICE
ORDER BY C.MAX_PRICE DESC

